### ISSUE TITLE
Add vue3 integration test

### ISSUE THREAD

**Issue by kelsos** [rotki/ui-library#16]
## Description

Add some minimal automated test that makes sure that the library works in vue3.
The test should be part of the CI.

## Tasks

- [ ] Create a small sample project with vue 3
- [ ] Adds minimal tests, maybe some basic component interaction that verifies that the library component loads and displays properly

**Comment by tewshi** [comment]
Hello @kelsos , just to be clear on this:
should the sample projects be part of the library? yes?

**Comment by tewshi** [comment]
got it.

**Comment by kelsos** [comment]
Done :)

**Comment by tewshi** [comment]
missed one in the description 😛
