### ISSUE TITLE
AutoComplete: create auto-complete component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#21]
[Figma Design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=580-55229&t=ttVz3vzOxnYJ4iYn-4)

should support:

- [ ] multiple selection
- [ ] single selection
- [ ] removable chips for multiple select

**Comment by lukicenturi** [comment]
I think we don't need this component yet for AccountCreation page (?)

**Comment by tewshi** [comment]
> I think we don't need this component yet for AccountCreation page (?)

I added it for Country field, it is more user friendly to have auto-complete in fields like these.

**Comment by lukicenturi** [comment]
> > I think we don't need this component yet for AccountCreation page (?)
> 
> I added it for Country field, it is more user friendly to have auto-complete in fields like these.

So it's for web, not the app right. Sorry didn't see it. Also in the figma I tried to find input that have arrow, didn't find it. 
But yes for the country we need to use autocomplete.
