### ISSUE TITLE
Recaptcha: Create re-captcha component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#22]
as seen here [Figma Design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=47-38470&t=BT00HLpRDPvYjbfp-4)

should support:

- [ ] validation
- [ ] timeout

**Comment by kelsos** [comment]
@rotki/frontend What do you think about this? I don't know if we should put it in the library. This is something specific to the website, so maybe we could instead implement it as part of the site only but provide any building blocks needed for this from the library itself.

**Comment by tewshi** [comment]
> @rotki/frontend What do you think about this? I don't know if we should put it in the library. This is something specific to the website, so maybe we could instead implement it as part of the site only but provide any building blocks needed for this from the library itself.

makes sense to have it in the app where needed, since we only need it on the website.

**Comment by kelsos** [comment]
Since this will not be part of the UI library I am gonna close the issue
